version: "3.8"
services:
  postgres:
    image: postgres:13.1
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 20

  adminer:
    image: adminer:4.8.0
    links:
      - postgres:db
    ports:
      - 8080:8080

  setup:
    image: node:12.20-alpine
    environment:
      NODE_ENV: development
    volumes:
      - .docker-data/node_modules:/usr/src/app/node_modules:cached
      - ./package.json:/usr/src/app/package.json:delegated
      - ./package-lock.json:/usr/src/app/package-lock.json:delegated
    working_dir: /usr/src/app
    entrypoint: ["npm", "install"]

  reset:
    image: node:12.20
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .docker-data/node_modules:/usr/src/app/node_modules:cached
      - ./package.json:/usr/src/app/package.json:delegated
      - ./package-lock.json:/usr/src/app/package-lock.json:delegated
      - ./src:/usr/src/app/src:delegated
    environment:
      NODE_ENV: development
      PGSTRING: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
    working_dir: /usr/src/app
    entrypoint: ["node", "src/dkr.partitions.reset.js"]

  producer:
    image: node:12.20
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .docker-data/node_modules:/usr/src/app/node_modules:cached
      - ./package.json:/usr/src/app/package.json:delegated
      - ./package-lock.json:/usr/src/app/package-lock.json:delegated
      - ./src:/usr/src/app/src:delegated
    environment:
      NODE_ENV: development
      PGSTRING: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      MAX_PARTITIONS: 40
      BATCH_SERIAL: 15
      BATCH_PARALLEL: 100
    working_dir: /usr/src/app
    entrypoint: ["node", "src/dkr.partitions.producer.js"]
    deploy:
      mode: replicated
      replicas: 3

  consumer1:
    image: node:12.20
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .docker-data/node_modules:/usr/src/app/node_modules:cached
      - ./package.json:/usr/src/app/package.json:delegated
      - ./package-lock.json:/usr/src/app/package-lock.json:delegated
      - ./src:/usr/src/app/src:delegated
    environment:
      NODE_ENV: development
      PGSTRING: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      CLIENT_ID: c1
      BATCH_PARALLEL: 10
    working_dir: /usr/src/app
    entrypoint: ["node", "src/dkr.partitions.consumer.js"]
    deploy:
      mode: replicated
      replicas: 3

  consumer2:
    image: node:12.20
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .docker-data/node_modules:/usr/src/app/node_modules:cached
      - ./package.json:/usr/src/app/package.json:delegated
      - ./package-lock.json:/usr/src/app/package-lock.json:delegated
      - ./src:/usr/src/app/src:delegated
    environment:
      NODE_ENV: development
      PGSTRING: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      CLIENT_ID: c2
      BATCH_PARALLEL: 10
    working_dir: /usr/src/app
    entrypoint: ["node", "src/dkr.partitions.consumer.js"]
    deploy:
      mode: replicated
      replicas: 3
